/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package cifa;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 11;
  /** RegularExpression Id. */
  int EXPONENT = 12;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int DFLT = 23;
  /** RegularExpression Id. */
  int SWITCH = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int SHORT = 28;
  /** RegularExpression Id. */
  int CASE = 29;
  /** RegularExpression Id. */
  int LONG = 30;
  /** RegularExpression Id. */
  int BOOL = 31;
  /** RegularExpression Id. */
  int _NUM_CHAR = 32;
  /** RegularExpression Id. */
  int _ESCAPED_CHAR = 33;
  /** RegularExpression Id. */
  int _TERM_START_CHAR = 34;
  /** RegularExpression Id. */
  int _TERM_CHAR = 35;
  /** RegularExpression Id. */
  int _WHITESPACE = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int FROM = 39;
  /** RegularExpression Id. */
  int DELETE = 40;
  /** RegularExpression Id. */
  int WHERE = 41;
  /** RegularExpression Id. */
  int INSERT = 42;
  /** RegularExpression Id. */
  int INTO = 43;
  /** RegularExpression Id. */
  int VALUES = 44;
  /** RegularExpression Id. */
  int SELECT = 45;
  /** RegularExpression Id. */
  int UPDATE = 46;
  /** RegularExpression Id. */
  int SET = 47;
  /** RegularExpression Id. */
  int CONTINUE = 48;
  /** RegularExpression Id. */
  int VOLATILE = 49;
  /** RegularExpression Id. */
  int REGISTER = 50;
  /** RegularExpression Id. */
  int UNSIGNED = 51;
  /** RegularExpression Id. */
  int TYPEDEF = 52;
  /** RegularExpression Id. */
  int SIZEOF = 53;
  /** RegularExpression Id. */
  int RETURN = 54;
  /** RegularExpression Id. */
  int EXTERN = 55;
  /** RegularExpression Id. */
  int STRUCT = 56;
  /** RegularExpression Id. */
  int STATIC = 57;
  /** RegularExpression Id. */
  int SIGNED = 58;
  /** RegularExpression Id. */
  int BREAK = 59;
  /** RegularExpression Id. */
  int UNION = 60;
  /** RegularExpression Id. */
  int CONST = 61;
  /** RegularExpression Id. */
  int ENUM = 62;
  /** RegularExpression Id. */
  int AUTO = 63;
  /** RegularExpression Id. */
  int GOTO = 64;
  /** RegularExpression Id. */
  int SQL = 65;
  /** RegularExpression Id. */
  int LT = 66;
  /** RegularExpression Id. */
  int LE = 67;
  /** RegularExpression Id. */
  int GT = 68;
  /** RegularExpression Id. */
  int GE = 69;
  /** RegularExpression Id. */
  int YU = 70;
  /** RegularExpression Id. */
  int HUO = 71;
  /** RegularExpression Id. */
  int GANTANHAO = 72;
  /** RegularExpression Id. */
  int SP = 73;
  /** RegularExpression Id. */
  int DH = 74;
  /** RegularExpression Id. */
  int COLON = 75;
  /** RegularExpression Id. */
  int LB = 76;
  /** RegularExpression Id. */
  int RB = 77;
  /** RegularExpression Id. */
  int YOUHUAKUO = 78;
  /** RegularExpression Id. */
  int ZUOHUAKUO = 79;
  /** RegularExpression Id. */
  int ZUOKUANGHAO = 80;
  /** RegularExpression Id. */
  int YOUKUANGHAO = 81;
  /** RegularExpression Id. */
  int DENGYUHAO = 82;
  /** RegularExpression Id. */
  int JINHAO = 83;
  /** RegularExpression Id. */
  int XIAOSHUDIAN = 84;
  /** RegularExpression Id. */
  int IDENTIFIER = 85;
  /** RegularExpression Id. */
  int LETTER = 86;
  /** RegularExpression Id. */
  int DIGIT = 87;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"int\"",
    "\"void\"",
    "\"main\"",
    "\"double\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"default\"",
    "\"switch\"",
    "\"do\"",
    "\"char\"",
    "\"float\"",
    "\"short\"",
    "\"case\"",
    "\"long\"",
    "\"bool\"",
    "<_NUM_CHAR>",
    "<_ESCAPED_CHAR>",
    "<_TERM_START_CHAR>",
    "<_TERM_CHAR>",
    "<_WHITESPACE>",
    "<OR>",
    "<AND>",
    "<FROM>",
    "<DELETE>",
    "<WHERE>",
    "<INSERT>",
    "<INTO>",
    "<VALUES>",
    "<SELECT>",
    "<UPDATE>",
    "<SET>",
    "\"continue\"",
    "\"volatile\"",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"sizeof\"",
    "\"return\"",
    "\"extern\"",
    "\"struct\"",
    "\"static\"",
    "\"signed\"",
    "\"break\"",
    "\"union\"",
    "\"const\"",
    "\"enum\"",
    "\"auto\"",
    "\"goto\"",
    "\"sql\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!=\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"}\"",
    "\"{\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"#\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
