/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 7.0.12 */
package cifa;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTTYPE = 2;
  public int JJTSENTENCEBLOCK = 3;
  public int JJTSENTENCE = 4;
  public int JJTSEQUENCESENTENCE = 5;
  public int JJTRETURNSENTENCE = 6;
  public int JJTSTATEMENTSENTENCE = 7;
  public int JJTASSIGNMENTSENTENCE = 8;
  public int JJTASSIGNMENTSENTENCE2 = 9;
  public int JJTCONDITIONSENTENCE = 10;
  public int JJTLOOPSENTENCE = 11;
  public int JJTCONDITION = 12;
  public int JJTROP = 13;
  public int JJTEXPRESSION = 14;
  public int JJTADDITIVEEXPRESSION = 15;
  public int JJTMULTIPLICATIVEEXPRESSION = 16;
  public int JJTUNARYEXPRESSION = 17;
  public int JJTIDENTIFIER = 18;
  public int JJTINTEGER = 19;
  public int JJTBOOLER = 20;
  public int JJTSWITCHSENTENCE = 21;
  public int JJTDOWHILE = 22;
  public int JJTFORSENTENCE = 23;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "Type",
    "SentenceBlock",
    "Sentence",
    "SequenceSentence",
    "ReturnSentence",
    "StatementSentence",
    "AssignmentSentence",
    "AssignmentSentence2",
    "ConditionSentence",
    "LoopSentence",
    "Condition",
    "Rop",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
    "Booler",
    "SwitchSentence",
    "DoWhile",
    "forSentence",
  };
}
/* JavaCC - OriginalChecksum=6a57aac018c39012903397bd1b9d7fc4 (do not edit this line) */
